---
- hosts: all
  sudo: true
  tasks:
    # Install Docker on Clients

    - name: install kernel backports
      apt: name={{ item }} update_cache=yes
      apt: name={{ item }} update_cache=yes
      with_items:
        - linux-image-generic-lts-raring
        - linux-headers-generic-lts-raring
      notify:
      - reboot server

    - name: add docker repository key
      apt_key: url=https://get.docker.io/gpg state=present

    - name: add docker repository to sources
      apt_repository: repo='deb https://get.docker.io/ubuntu docker main' state=present

    - name: install docker package
      apt: update_cache=yes
      apt: name=lxc-docker

    # Install Ansible Docker Task Requirements

    - name: install python-pip
      apt: name=python-pip

    - name: install docker-py
      pip: name=docker-py

    # Open Required Ports

    - name: allow ssh port through firewall
      ufw: rule=allow port={{ ansible_ssh_port }} proto=tcp state=enabled
      notify:
      - reboot server

  handlers:
    - name: reboot server
      command: /sbin/reboot
      notify:
        - wait for startup

    - name: wait for startup
      sudo: false
      local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port }} state=started
