---
- hosts: appservers
  sudo: true
  tasks:
    - name: checkout bmorrall/rails-common repo
      git:
        repo: https://github.com/bmorrall/docker-rails-common.git
        version: spike/baserails
        dest: /apps/rails-common/src

    - name: build bmorrall/rails-common image
      docker_image:
        path: /apps/rails-common/src
        name: bmorrall/rails-common
        state: present

    - name: checkout bmorrall/please-ignore repo
      git:
        repo: https://github.com/bmorrall/PleaseIgnore.git
        version: spike/nginx-config
        dest: /apps/please-ignore/src

    - name: build bmorrall/please-ignore image
      docker_image:
        path: /apps/please-ignore/src
        name: bmorrall/please-ignore
        state: present

    - name: remove existing container
      docker:
        image: bmorrall/please-ignore
        name: please_ignore
        state: absent

    - name: start bmorrall/please-ignore container
      docker:
        image: bmorrall/please-ignore
        name: please_ignore
        state: running
        env:
          - DATABASE_URL=postgres://docker:docker@{{ database_host }}/docker
          - SECRET_KEY_BASE={{ please_ignore_secret_key }}
          - DEVISE_SECRET_KEY={{ please_ignore_devise_secret }}
        ports:
          - 8080:8080
        volumes:
          - /apps/please-ignore/log:/apps/please-ignore/log

    - name: setup nginx configuration
      command: cp /apps/please-ignore/etc/container/staging-nginx-sites.conf /apps/nginx/sites-enabled/default

    - name: stop nginx container
      docker:
        image: dockerfile/nginx
        name: nginx
        state: absent

    - name: start nginx container
      docker:
        image: dockerfile/nginx
        name: nginx
        links:
          - please_ignore
        ports:
          - 80:80
          # - 443:443
        volumes:
          - /apps/nginx/sites-enabled:/etc/nginx/sites-enabled
          - /apps/nginx/logs:/var/log/nginx

    - name: allow port 80 through firewall
      ufw: rule=allow port=80 proto=tcp
      notify: reboot server

  handlers:
    - name: reboot server
      command: /sbin/reboot
      notify:
        - wait for startup

    - name: wait for startup
      sudo: false
      local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port }} state=started
 
