---
- hosts: services
  sudo: true
  tasks:
    - name: start pg container
      docker:
        image: paintedfox/postgresql
        name: postgres
        ports:
          - 5432:5432
        env: USER=docker,PASS=docker,DB=docker
        volumes:
          - /apps/postgres/data:/data
          - /apps/postgres/logs:/var/log/postgresql

    - name: allow port 5432 through firewall
      ufw: rule=allow port=5432 proto=tcp
      notify: reboot server

  handlers:
    - name: reboot server
      command: /sbin/reboot
      notify:
        - wait for startup

    - name: wait for startup
      sudo: false
      local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port }} state=started
  